version: '3.8'

services:
  frontend:
    build:
      context: ./React/myapp
      dockerfile: Dockerfile.react
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./Spring/demo
      dockerfile: Dockerfile.spring
    ports:
      - "8080:8080"
